name: Build Unblockt for Mac

on: workflow_dispatch

jobs:
  build:

    runs-on: macos-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up environment
        run: |
          cd build-scripts
          ./environment-mac.sh
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build
        run: |
          cd build-scripts
          ./package-extension-mac.sh
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: unblockt.vsix
          path: extension/unblockt-*.vsix